### ISSUE TITLE
very inefficient collection of course/assignment data

### ISSUE THREAD

**Issue by danmarsden** [philip-raschke/moodle-block_assignments#1]
Looks like an interesting idea - a quick look at your get_content() function shows multiple calls to get an individual course record from the database within various loops. for example - you get the course records from enrol_get_my_courses then you iterate over each to get the assignments, then you iterate over each assignment and get the course record again - then later in the loop you obtain the course record from the database again when you already have it in the $course var

it would be really good if you could restructure the database calls so that you get everything you need at the top of the function rather than multiple db calls within each loop.

It might also be good if you modified your call to populate $assigngrades so that it includes the course and assignment information needed rather than iterate over each $assigngrades and get the course and then the assignment.

**Comment by mudrd8mz** [comment]
Older yet still valid thread at moodle.org related to this: https://moodle.org/mod/forum/discuss.php?d=98273

**Comment by philip-raschke** [comment]
Thanks for your feedback. You're right the way of collecting the data was very inefficient. I fixed this issue now by collecting all relevant data at startup as you suggested.

**Comment by mudrd8mz** [comment]
Hmm. Well, it looks better indeed. Yet still there is `$DB->get_records()` called from within the loop. The point leading to higher scalability is to try hard to have constant number of SQL queries to obtain all required data - by making use of table JOINs and `$DB->get_in_or_equals()`.

**Comment by philip-raschke** [comment]
I tried to use a LEFT JOIN to retrieve the assignments data and the grades data in one query but ran into an issue. I used the following query:

``` sql
SELECT * FROM `mdl_assign` as a LEFT JOIN `mdl_assign_grades` as b 
ON a.id = b.assignment AND `course` IN (X) AND (b.userid = Y OR b.userid = NULL)
```

In phpMyAdmin I get results as expected yet when calling `$DB->get_records_sql()` passing the query as parameter I only get the graded assignments. What am I doing wrong?

**Comment by danmarsden** [comment]
It's probably important to first realise that Moodle supports multiple db types and what might work as in-line sql on one database type will not work on others, Moodle provides a number of helper functions to deal with this. there are some mysql specific components to your current sql. the "mdl_" prefix can also change between moodle installations and you should remove the backticks too. Take a look at the other examples in the code - a search for "$sql" will probably find a few different examples.

firstly - table names should be specified like:
{assign}  
not
`mdl_assign`

the moodle functions will then automatically add the correct prefix (eg mdl_)

We don't usually use "as" when assigning a var to a table name - usually we'll do:
SELECT \* from {assign} a
LEFT JOIN {assign_grades} b
ON a.id = b.assignment

`course` isn't well defined - you should use a.course or b.course (without the backticks) and you shold also use the helper function $DB->get_in_or_equal instead of hard-coding IN (x) within in-line sql

hopefully that will get you on the right track!

**Comment by mudrd8mz** [comment]
Some of these summarised in https://docs.moodle.org/dev/SQL_coding_style

**Comment by philip-raschke** [comment]
First, thanks for your feedback. I now reduced the number of SQL queries to 2 with the following code:

``` php
list($insql, $inparams) = $DB->get_in_or_equal($courseids);
$sql = 'SELECT *
        FROM {assign}
        WHERE course '.$insql;
$assignments = $DB->get_records_sql($sql, $inparams);

$sql = 'SELECT *
        FROM {assign_grades}
        WHERE userid = ?';
$assigngrades = $DB->get_records_sql($sql, array($USER->id));
```

I actually wanted to gather the relevant data within one query with the following code:

``` php
list($insql, $inparams) = $DB->get_in_or_equal($courseids);
$sql = 'SELECT * 
        FROM {assign} a 
        LEFT JOIN {assign_grades} b ON (a.id = b.assignment OR b.assignment IS NULL)
        WHERE a.course '.$insql.' 
        AND b.userid = ?
        OR b.userid IS NULL';
array_push($inparams, $USER->id);
$all = $DB->get_records_sql($sql, $inparams);
```

The problem is that in this case `$all` only contains rows that have entries in both tables `{assign}` and `{assign_grades}`. In phpMyAdmin I get a different result. There I get all assignments and if available their respective grade. In case there is no grade for the assignment the values are simply `NULL`. I checked the implementation of `get_records_sql()` but found no possibility to solve this.

The second problem is that `{assign}` and `{assign_grades}` both have columns with the same name `grade` and only one value will be available in `$all`. One value will be overwritten if joining the tables, so it seems that this is not the right way.

**Comment by danmarsden** [comment]
I don't have time to look at those queries much sorry - it's usually pretty acceptable to make 2 or more queries to return the data you need - it's just good to avoid doing a db call inside a loop if you can as this can significantly impact performance (although it's sometimes not always easy to do this.)

**Comment by philip-raschke** [comment]
Hi Dan, I understand. I will upload the current version to the Moodle Plugin Repository.
