### ISSUE TITLE
non-object notice

### ISSUE THREAD

**Issue by rimacher** [philip-raschke/moodle-block_assignments#5]
Hello Philip,

I'm getting the following errors:

Notice: Undefined offset: 422 in /data/moodlegit/moodle/blocks/assignments/block_assignments.php on line 100

Notice: Trying to get property of non-object in /data/moodlegit/moodle/blocks/assignments/block_assignments.php on line 101

Notice: Trying to get property of non-object in /data/moodlegit/moodle/blocks/assignments/block_assignments.php on line 102

Notice: Undefined index: in /data/moodlegit/moodle/blocks/assignments/block_assignments.php on line 102

Notice: Trying to get property of non-object in /data/moodlegit/moodle/blocks/assignments/block_assignments.php on line 111

Notice: Trying to get property of non-object in /data/moodlegit/moodle/blocks/assignments/block_assignments.php on line 111

Notice: Undefined index: in /data/moodlegit/moodle/blocks/assignments/block_assignments.php on line 111

Fatal error: Call to a member function out() on a non-object in /data/moodlegit/moodle/blocks/assignments/block_assignments.php on line 111

**Comment by philip-raschke** [comment]
Hmm ... very interesting. I don't get an error in any of my test cases. Can you give me more information. Which PHP version do you use? Which Moodle version do you use? Do you get this error before or after you logged in?

**Comment by rimacher** [comment]
We use PHP Version 5.4.16, Moodle 2.8.6 (Build: 20150528). I get it right after logging in as a student. Logging in as admin doesn't give those errors.

**Comment by philip-raschke** [comment]
Hi rimacher, I finally found the error and was able to fix it. You find the most recent version (1.0.6) on the [Moodle Plugin Repository](https://moodle.org/plugins/view/block_assignments) page or by pulling this repo. Please tell me if your problem is solved by this fix.

**Comment by rimacher** [comment]
Yes, that fixed it. Thank you.
